[2024-05-18T23:57:27.436+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T23:57:27.560+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:21:00+00:00 [queued]>
[2024-05-18T23:57:27.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:21:00+00:00 [queued]>
[2024-05-18T23:57:27.595+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-18T23:57:27.649+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): Process_and_Send_Data_to_DB> on 2024-05-18 12:21:00+00:00
[2024-05-18T23:57:27.737+0000] {standard_task_runner.py:63} INFO - Started process 176 to run task
[2024-05-18T23:57:27.848+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Real_Estate_Webscraping_ETL', 'Process_and_Send_Data_to_DB', 'scheduled__2024-05-18T12:21:00+00:00', '--job-id', '395', '--raw', '--subdir', 'DAGS_FOLDER/webscrapping.py', '--cfg-path', '/tmp/tmpstdp55aj']
[2024-05-18T23:57:27.897+0000] {standard_task_runner.py:91} INFO - Job 395: Subtask Process_and_Send_Data_to_DB
[2024-05-18T23:57:28.406+0000] {task_command.py:426} INFO - Running <TaskInstance: Real_Estate_Webscraping_ETL.Process_and_Send_Data_to_DB scheduled__2024-05-18T12:21:00+00:00 [running]> on host 7879427f0394
[2024-05-18T23:57:28.762+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='svc' AIRFLOW_CTX_DAG_ID='Real_Estate_Webscraping_ETL' AIRFLOW_CTX_TASK_ID='Process_and_Send_Data_to_DB' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T12:21:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-18T12:21:00+00:00'
[2024-05-18T23:57:28.772+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T23:57:29.021+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-05-18T23:57:29.035+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,com.datastax.spark:spark-cassandra-connector_2.12:3.5.0,org.apache.kafka:kafka-clients:3.5.1,commons-logging:commons-logging:1.2 --name arrow-spark --deploy-mode client dags/includes/jobs/spark_consumer.py
[2024-05-18T23:57:29.579+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-05-18T23:59:34.783+0000] {spark_submit.py:571} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-05-18T23:59:39.963+0000] {spark_submit.py:571} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2024-05-18T23:59:40.101+0000] {spark_submit.py:571} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2024-05-18T23:59:40.491+0000] {spark_submit.py:571} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2024-05-18T23:59:40.639+0000] {spark_submit.py:571} INFO - com.datastax.spark#spark-cassandra-connector_2.12 added as a dependency
[2024-05-18T23:59:40.644+0000] {spark_submit.py:571} INFO - org.apache.kafka#kafka-clients added as a dependency
[2024-05-18T23:59:40.652+0000] {spark_submit.py:571} INFO - commons-logging#commons-logging added as a dependency
[2024-05-18T23:59:40.653+0000] {spark_submit.py:571} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-ee2d8592-c037-431c-a397-c44c66c205df;1.0
[2024-05-18T23:59:40.658+0000] {spark_submit.py:571} INFO - confs: [default]
[2024-05-19T00:00:22.964+0000] {spark_submit.py:571} INFO - found com.datastax.spark#spark-cassandra-connector_2.12;3.5.0 in central
[2024-05-19T00:00:25.267+0000] {spark_submit.py:571} INFO - found com.datastax.spark#spark-cassandra-connector-driver_2.12;3.5.0 in central
[2024-05-19T00:00:26.565+0000] {spark_submit.py:571} INFO - found org.scala-lang.modules#scala-collection-compat_2.12;2.11.0 in central
[2024-05-19T00:00:49.951+0000] {spark_submit.py:571} INFO - found com.datastax.oss#java-driver-core-shaded;4.13.0 in central
[2024-05-19T00:00:53.486+0000] {spark_submit.py:571} INFO - found com.datastax.oss#native-protocol;1.5.0 in central
[2024-05-19T00:00:57.714+0000] {spark_submit.py:571} INFO - found com.datastax.oss#java-driver-shaded-guava;25.1-jre-graal-sub-1 in central
[2024-05-19T00:01:05.394+0000] {spark_submit.py:571} INFO - found com.typesafe#config;1.4.1 in central
[2024-05-19T00:01:10.821+0000] {spark_submit.py:571} INFO - found org.slf4j#slf4j-api;1.7.26 in central
[2024-05-19T00:01:23.912+0000] {spark_submit.py:571} INFO - found io.dropwizard.metrics#metrics-core;4.1.18 in central
[2024-05-19T00:01:25.674+0000] {spark_submit.py:571} INFO - found org.hdrhistogram#HdrHistogram;2.1.12 in central
[2024-05-19T00:01:27.274+0000] {spark_submit.py:571} INFO - found org.reactivestreams#reactive-streams;1.0.3 in central
[2024-05-19T00:01:32.189+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-05-19T00:01:33.947+0000] {process_utils.py:132} INFO - Sending 15 to group 176. PIDs of all processes in the group: [181, 176]
[2024-05-19T00:01:34.032+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 176
[2024-05-19T00:01:34.098+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-19T00:01:34.177+0000] {spark_submit.py:697} INFO - Sending kill signal to spark-submit
[2024-05-19T00:01:34.774+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T00:01:40.146+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 490, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 539, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-05-19T00:01:40.360+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Real_Estate_Webscraping_ETL, task_id=Process_and_Send_Data_to_DB, run_id=scheduled__2024-05-18T12:21:00+00:00, execution_date=20240518T122100, start_date=20240518T235727, end_date=20240519T000140
[2024-05-19T00:01:41.185+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=176, status='terminated', exitcode=2, started='23:57:27') (176) terminated with exit code 2
[2024-05-19T00:01:41.227+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=181, status='terminated', started='23:57:28') (181) terminated with exit code None
[2024-05-19T00:01:41.268+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
